# Generated by Django 2.1.4 on 2019-04-01 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calendar',
        ),
        migrations.DeleteModel(
            name='Days',
        ),
        migrations.DeleteModel(
            name='Months',
        ),
    ]
