# Generated by Django 2.1.5 on 2019-04-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_auto_20190403_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='course',
            field=models.TextField(blank=True),
        ),
    ]
