# Generated by Django 2.1.4 on 2019-04-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_event_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
