# Generated by Django 2.1.4 on 2019-04-28 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_auto_20190419_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2019, 4, 28)),
        ),
    ]
