# Generated by Django 2.2.1 on 2019-05-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_auto_20190428_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='course',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
