# Generated by Django 2.2.1 on 2019-05-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_auto_20190510_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='course_year',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('NA', 'No Associated Class Year')], default='NA', max_length=2),
        ),
    ]
